services:
  npm:
    image: jc21/nginx-proxy-manager:latest    
    container_name: box-npm
    hostname: box-npm    
    environment:
      - TZ=Asia/Singapore
      - PUID=1000
      - PGID=1000
      - NGINX_HOST=npm.box.z4zai.com
      - NGINX_PORT=80
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 81:81/tcp 
    expose:
      - 80
      - 443
      - 81
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 30s
      timeout: 3s
    volumes:
      - /home/zdin/docker/nginxr/data:/data
      - /home/zdin/docker/nginx/letsencrypt:/etc/letsencrypt
      - /home/zdin/docker/nginx/templates:/etc/nginx/templates
      - /home/zdin/docker/nginx/web:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=http"
      - "traefik.http.routers.nginx.rule=Host(`npm.box.z4zai.com`)"
      - "traefik.http.middlewares.nginx-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nginx.middlewares=nginx-https-redirect"
      - "traefik.http.routers.nginx-secure.entrypoints=https"
      - "traefik.http.routers.nginx-secure.rule=Host(`npm.box.z4zai.com`)"
      - "traefik.http.routers.nginx-secure.tls=true"
      - "traefik.http.routers.nginx-secure.service=nginx"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      - "traefik.http.routers.nginx-secure.middlewares=middlewares-authentik@file"
      - "traefik.docker.network=frontstack"
    networks:
      - frontstack
    security_opt:
      - no-new-privileges:true

      
  goaccess:
    image: xavierh/goaccess-for-nginxproxymanager:latest
    container_name: goaccess
    restart: always
    ports:
      - '7880:7880'
    expose:
      - 7880
    volumes:
      - /home/zdin/docker/nginx-proxy-manager/data/logs:/opt/log:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
      - SKIP_ARCHIVED_LOGS=False
      - BASIC_AUTH=True
      - BASIC_AUTH_USERNAME=zdin
      - BASIC_AUTH_PASSWORD=co-pilot-is-my-best-friend
networks:
  frontstack:
    external: true
